
.PHONY : test
test :
	istari-nolib -no regression.ist
	istari -no typedef.ist
	istari -no withlib.ist
	istari -no quotient.ist
	istari -no omegatest.ist
	istari -no rewriting.ist
	istari-nolib namespace.ist
	istari -no ../docs/datatype-induction.ist
	istari -no ../docs/hailstone.ist
	istari -no old-typechecker.ist
