
.PHONY : test
test :
	istari-nolib -no regression.ist
	istari -no typedef.ist
	istari -no withlib.ist
	istari -no datatype-induction.ist
	istari -no quotient.ist
	istari -no omegatest.ist
	istari -no rewriting.ist
	istari-nolib namespace.ist

