
include cmlib.make

# .ipc files need their dependencies given explicitly
from_string.cmi from_string.cmo : from_string_sig.cmi
bytestring.cmi bytestring.cmo : bytestring_sig.cmi
convert_word.cmi convert_word.cmo : convert_word_sig.cmi bytestring.cmi

ocaml : $(OBJS)
	ocamlc -a -o cmlib.cma $(OBJS)
